theme: jekyll-theme-minimal
collections:
  shader:
    output: true

baseurl: /visual-complexity
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "shader"
    values:
      layout: "shader"
